AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names tag name
    Type: String
  VpcCIDR:
    Description: VPC CIDR Ip
    Type: String
    Default: 10.0.0.0/16

Resources:
# VPC setting
  VPC:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: !Ref VpcCIDR
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName

  
