Parameters:
  VPC:
    Description: Specify VPC Id for ALB
    Type: AWS::EC2::VPC::ID
  PublicSubnet1:
    Description: Specify Subnet1 Id for ALB
    Type: AWS::EC2::Subnet::Id
  PublicSubnet2:
    Description: Specify Subnet2 Id for ALB
    Type: AWS::EC2::Subnet::Id
  EC2Instance1:
    Description: Specify Istance1 Id for ALB
    Type: AWS::EC2::Instance::Id
  EC2Instance2:
    Description: Specify Instance2 Id for ALB
    Type: AWS::EC2::Instance::Id
  ELBSecurityGroup:
    Description: Specify SG for ALB
    Type: AWS::EC2::SecurityGroup::ID


Resources: 
  EC2TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 30
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 15
      HealthyThresholdCount: 5
      Matcher:
        HttpCode: '200'
      Name: EC2TargetGroup
      Port: 80
      Protocol: HTTP
      TargetGroupAttributes:
      - Key: deregistration_delay.timeout_seconds
        Value: '20'
      Targets:
      - Id: !Ref EC2Instance1
        Port: 80
      - Id: !Ref EC2Instance2
        Port: 80
      UnhealthyThresholdCount: 3
      VpcId: !Ref VPC

  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      Subnets: 
      - !Ref PublicSubnet1
      - !Ref PublicSubnet2
      SecurityGroups:
        - !GetAtt ELBSecurityGroup.GroupId
        
  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref EC2TargetGroup 
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP

